export const PERMISSIONS = {
  VIEW_DASHBOARD: "VIEW_DASHBOARD",
  CREATE_USER: "CREATE_USER",
  UPDATE_USER: "UPDATE_USER",
  ALL_USER: "ALL_USER",
  DELETE_USER: "DELETE_USER",

  ALBUM_VIEW: "ALBUM_VIEW",
  ALBUM_EDIT: "ALBUM_EDIT",
  
  ARTIST_VIEW: "ARTIST_VIEW",
  ARTIST_EDIT: "ARTIST_EDIT",

  GENRE_VIEW: "GENRE_VIEW",
  GENRE_EDIT: "GENRE_EDIT",
  
  PLAYLIST_VIEW: "PLAYLIST_VIEW",
  PLAYLIST_EDIT: "PLAYLIST_EDIT",
  
  PROMOTION_VIEW: "PROMOTION_VIEW",
  PROMOTION_EDIT: "PROMOTION_EDIT",
  
  REVIEW_VIEW: "REVIEW_VIEW",
  REVIEW_EDIT: "REVIEW_EDIT",
  
  SONG_VIEW: "SONG_VIEW",
  SONG_EDIT: "SONG_EDIT",
  
  STATION_VIEW: "STATION_VIEW",
  STATION_EDIT: "STATION_EDIT",
  
  SUBSCRIPTION_PLAN_VIEW: "SUBSCRIPTION_PLAN_VIEW",
  SUBSCRIPTION_PLAN_EDIT: "SUBSCRIPTION_PLAN_EDIT",
} as const;

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];
